Repository bardia-p/carleton-mail-delivery-robot, pull requests merged in 2024-02, with the labels that each got.

#31 Adding csv files for map and beacon orientations
  mail_delivery_robot/config/beacon_connections.csv
  mail_delivery_robot/config/map.csv
Labels: navigation

#32 Fixed the issue with the parser by moving the files to install.
  mail_delivery_robot/setup.py
Labels: bug

#34 Adding Gantt Chart PNG and PUML files
  diagrams/gantt_fall.png
  diagrams/gantt_winter.png
  diagrams/src/plantuml_files/ganttchart.puml
Labels: documentation

#35 Updated the filenames to fix the diagrams.
  diagrams/component_diagram.png
  diagrams/gantt_fall.png
  diagrams/gantt_winter.png
  diagrams/ganttchart.png
  diagrams/src/plantuml_files/ganttchart.plantuml
Labels: bug, documentation

#38 Updating constants with beacon threshold
  mail_delivery_robot/config/config.csv
  mail_delivery_robot/control/robot_driver.py
  mail_delivery_robot/perceptions/lidar_sensor.py
Labels: bug, control

#43 Resolve Issue: Dynamic Navigation
  mail_delivery_robot/config/beacons.csv
  mail_delivery_robot/config/config.csv
  mail_delivery_robot/config/map.csv
  mail_delivery_robot/navigation/captain.py
  mail_delivery_robot/navigation/map.py
  mail_delivery_robot/perceptions/beacon_sensor.py
  mail_delivery_robot/setup.py
  mail_delivery_robot/tools/nav_parser.py
Labels: feature, navigation

#44 Implemented integration testing and created a simulator
  mail_delivery_robot/config/beacon_connections.csv
  mail_delivery_robot/config/map.csv
  mail_delivery_robot/control/action_translator.py
  mail_delivery_robot/launch/test.launch.py
  mail_delivery_robot/navigation/captain.py
  mail_delivery_robot/setup.py
  mail_delivery_robot/stubs/__init__.py
  mail_delivery_robot/stubs/stub_sensor.py
Labels: test

#45 U-Turn Command for the Robot
  mail_delivery_robot/config/config.csv
  mail_delivery_robot/control/action_translator.py
  mail_delivery_robot/control/state_machine.py
  mail_delivery_robot/test/test_state_machine.py
Labels: feature, navigation
